### ISSUE TITLE
"object has no attribute 'create_pipe_connection" Error??

### ISSUE THREAD

**Issue by Cappyadams** [davehornik/sd-discord-rich_presence#12]
so, I just installed the extension, restarted WebUI and got this error thing
```
*** Error executing callback ui_tabs_callback for D:\Stable\stable-diffusion-webui-directml-master\stable-diffusion-webui-directml-master\extensions\sd-discord-rich_presence\scripts\main.py
    Traceback (most recent call last):
      File "D:\Stable\stable-diffusion-webui-directml-master\stable-diffusion-webui-directml-master\modules\script_callbacks.py", line 153, in ui_tabs_callback
        res += c.callback() or []
      File "D:\Stable\stable-diffusion-webui-directml-master\stable-diffusion-webui-directml-master\extensions\sd-discord-rich_presence\scripts\main.py", line 138, in on_ui_tabs
        discord_broadcast()
      File "D:\Stable\stable-diffusion-webui-directml-master\stable-diffusion-webui-directml-master\extensions\sd-discord-rich_presence\scripts\main.py", line 25, in discord_broadcast
        broadcast.connect()
      File "D:\Stable\stable-diffusion-webui-directml-master\stable-diffusion-webui-directml-master\venv\lib\site-packages\pypresence\presence.py", line 43, in connect
        self.loop.run_until_complete(self.handshake())
      File "C:\Users\distd\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
        return future.result()
      File "D:\Stable\stable-diffusion-webui-directml-master\stable-diffusion-webui-directml-master\venv\lib\site-packages\pypresence\baseclient.py", line 116, in handshake
        self.sock_writer, _ = await asyncio.wait_for(self.loop.create_pipe_connection(lambda: reader_protocol, ipc_path), self.connection_timeout)
    AttributeError: '_WindowsSelectorEventLoop' object has no attribute 'create_pipe_connection'
```
Am I doing something wrong or is this a bug?

**Comment by KIZILANDO** [comment]
> so, I just installed the extension, restarted WebUI and got this error thing
> 
> ```
> *** Error executing callback ui_tabs_callback for D:\Stable\stable-diffusion-webui-directml-master\stable-diffusion-webui-directml-master\extensions\sd-discord-rich_presence\scripts\main.py
>     Traceback (most recent call last):
>       File "D:\Stable\stable-diffusion-webui-directml-master\stable-diffusion-webui-directml-master\modules\script_callbacks.py", line 153, in ui_tabs_callback
>         res += c.callback() or []
>       File "D:\Stable\stable-diffusion-webui-directml-master\stable-diffusion-webui-directml-master\extensions\sd-discord-rich_presence\scripts\main.py", line 138, in on_ui_tabs
>         discord_broadcast()
>       File "D:\Stable\stable-diffusion-webui-directml-master\stable-diffusion-webui-directml-master\extensions\sd-discord-rich_presence\scripts\main.py", line 25, in discord_broadcast
>         broadcast.connect()
>       File "D:\Stable\stable-diffusion-webui-directml-master\stable-diffusion-webui-directml-master\venv\lib\site-packages\pypresence\presence.py", line 43, in connect
>         self.loop.run_until_complete(self.handshake())
>       File "C:\Users\distd\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
>         return future.result()
>       File "D:\Stable\stable-diffusion-webui-directml-master\stable-diffusion-webui-directml-master\venv\lib\site-packages\pypresence\baseclient.py", line 116, in handshake
>         self.sock_writer, _ = await asyncio.wait_for(self.loop.create_pipe_connection(lambda: reader_protocol, ipc_path), self.connection_timeout)
>     AttributeError: '_WindowsSelectorEventLoop' object has no attribute 'create_pipe_connection'
> ```
> 
> Am I doing something wrong or is this a bug?

https://github.com/davehornik/sd-discord-rich_presence/issues/11#issuecomment-1732559851

**Comment by marduk191** [comment]
https://github.com/davehornik/sd-discord-rich_presence/pull/13/commits/9c6a74c4947555e07a27cee023e8f9a5d82cce01 fixes this

**Comment by davehornik** [comment]
https://github.com/davehornik/sd-discord-rich_presence/commit/b3767a195f1748c5453a96c0b7de295030fdcb41
