### ISSUE TITLE
any differences from other implementation?

### ISSUE THREAD

**Issue by pixelqiwi** [davehornik/sd-discord-rich_presence#4]
is this extension any different from [this one](https://github.com/kamfretoz/stable-diffusion-webui-discord-rpc)? 
like it seems to do the same thing, except yours has like thrice the amount of code

**Comment by Edesak** [comment]
The difference is we provide number of images you generating, He is only providing sampling steps. That means when you generating for example 10 batch samples with 3 batch size it will restart you sampling steps. We provide the information of number of images, in this example i provided it is 30 images you trying to make. 

Plus he is not considering the time you spending for generating. In ours it shows how much you are in Idle mode and how much time you are in generating mode. 

Bit of sneak peak but we considering to add some kind of status in what stage of the generating you are but we will see :). 

But the repository you provided should be functional. If you don`t care about these extra information. 

Short answer: Yes there is difference. 

Any more questions or i can close your issue ?

**Comment by Edesak** [comment]
this issue is here more then 2 days i'm closing it then
