### ISSUE TITLE
Progress indicator does not work

### ISSUE THREAD

**Issue by sergiohzph** [davehornik/sd-discord-rich_presence#6]
![image](https://user-images.githubusercontent.com/124453184/233336305-f88ca7b5-afae-44e3-8e0d-811e148014eb.png)
As you can see, it says all the time that it is at 0% of the total progress, when a few minutes have passed, and the real progress is this:
![image](https://user-images.githubusercontent.com/124453184/233336363-b9541e21-ba1d-46bf-bfc3-0ea5a3079aab.png)

**Comment by Edesak** [comment]
Hmm that is odd. Have you reloaded your UI ? We have an issue with the reload UI function where when you reload your UI it creates new instance of the connection to your discord, still didn't solve it tho. 

Try rerun the A1111 if the problem persist can you give us more info like is it txt2img or img2img? Are you running on CPU or GPU? Is there something special you using while generating like addon or smth like that. We then try to replicate the problem and find the issue. 

Be sure to try the first suggested. Rerun your A1111.

**Comment by sergiohzph** [comment]
> Hmm that is odd. Have you reloaded your UI ? We have an issue with the reload UI function where when you reload your UI it creates new instance of the connection to your discord, still didn't solve it tho.
Ah yes, I've reloaded it because after each bulk generation sequence it gets buggy, but that's a issue of the A1111's GUI.
> Try rerun the A1111 if the problem persist can you give us more info like is it txt2img or img2img? Are you running on CPU or GPU? Is there something special you using while generating like addon or smth like that. We then try to replicate the problem and find the issue.
Yeah, I've restarted it few times and I still have the issue, I'm just doing txt2img, running on GPU and I'm not using any special extension.
> Be sure to try the first suggested. Rerun your A1111.
I've already done that, even I restarted my computer and it's still not working.

**Comment by Edesak** [comment]
It is really hard to determinate where is the problem. It is all functioning on our side. Can you contact me on discord where we could resolve your problem ? Edesak#5182 or are you comfortable with that ? I need more details to get bottom of this.  

Ofc after we resolve the problem i will write it here what was it or correct the code.

**Comment by davehornik** [comment]
> ![image](https://user-images.githubusercontent.com/124453184/233336305-f88ca7b5-afae-44e3-8e0d-811e148014eb.png) As you can see, it says all the time that it is at 0% of the total progress, when a few minutes have passed, and the real progress is this: ![image](https://user-images.githubusercontent.com/124453184/233336363-b9541e21-ba1d-46bf-bfc3-0ea5a3079aab.png)

Do you have warnings in console enabled? Nothing in there?
Also have you tried re-installing the extension? It can be issue with module "pypresence" that is not co-working with the Discord for some reason. Everything else is working as inteded?

**Comment by sergiohzph** [comment]
> Do you have warnings in console enabled? Nothing in there? Also have you tried re-installing the extension? It can be issue with module "pypresence" that is not co-working with the Discord for some reason. Everything else is working as intended?

I just reainstalled it and it's still being stuck at 0%, there are no warnings: 
![image](https://user-images.githubusercontent.com/124453184/233739372-ab7ad234-177a-41ca-8b37-ca9ede55deb6.png)





> It is really hard to determinate where is the problem. It is all functioning on our side. Can you contact me on discord where we could resolve your problem ? Edesak#5182 or are you comfortable with that ? I need more details to get bottom of this.
> 
> Ofc after we resolve the problem i will write it here what was it or correct the code.

Sure, I've added you.

**Comment by sergiohzph** [comment]
By the way, I found another bug. When I change model and start a new generation in rich presence it still appears as if I am using the previous model. I have to restart Discord and A1111 to show the new model I'm using.

**Comment by Edesak** [comment]
The problem was due to mix matching python versions. Be sure to have your environment right.
