### ISSUE TITLE
[BUG] problems with the vladmadic/automatic fork

### ISSUE THREAD

**Issue by IkariDevGIT** [davehornik/sd-discord-rich_presence#7]
**Describe the bug**

**To Reproduce**
1. Use https://github.com/vladmandic/automatic fork on the newest version(aka commit bb438efed47d5ed064ea5933cccc009d8549d4cb)
2. Install sd-discord-rich_presence
3. Restart the web UI completely(reopen)

**Expected behavior**
I expected the extension to load normally

**Screenshots**
![grafik](https://user-images.githubusercontent.com/90197782/234333593-1fff4e80-f0be-467f-b90e-cf0b3855d0e2.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser firefox
 - Version 112.0.1 (64-Bit)

**Comment by davehornik** [comment]
Hey!
We do not know nothing about this forked repo, and it is obvious that it is different from AUTOMATICs webui.
So, if there is different folder/file structure it can't work as intended.

And we do not support any other than the [original one.](https://github.com/AUTOMATIC1111/stable-diffusion-webui).
If you have any problem with installation on the original fork, feel free to open new issue.
