### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by Kepler-16b** [davehornik/sd-discord-rich_presence#8]
I installed through A1111 extension tab. restart the program and generate some images. But no status is showing in my discord profile. Do I need extra steps to set up this extension?

**Comment by davehornik** [comment]
What does it say in console?
Start it fresh, generate one img and copy paste the log (or scrnsht with all info)

**Comment by Kepler-16b** [comment]
<details><summary>the console log</summary><p>

---

Launching Web UI with arguments: --theme dark --xformers --upcast-sampling --opt-channelslast --disable-nan-check --autolaunch --administrator

Civitai Helper: Get Custom Model Folder
Civitai Helper: Load setting from: K:\Automatic1111-Stable-Diffusion\extensions\Stable-Diffusion-Webui-Civitai-Helper\setting.json
Civitai Helper: Set Proxy: http://127.0.0.1:10809
Additional Network extension not installed, Only hijack built-in lora
LoCon Extension hijack built-in lora successfully
ControlNet v1.1.121
ControlNet v1.1.121
Loading weights [cbfba64e66] from K:\Automatic1111-Stable-Diffusion\models\Stable-diffusion\Anime\CounterfeitV30_v30.safetensors
K:\Automatic1111-Stable-Diffusion\py310\lib\site-packages\safetensors\torch.py:99: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  with safe_open(filename, framework="pt", device=device) as f:
K:\Automatic1111-Stable-Diffusion\py310\lib\site-packages\torch\_utils.py:776: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  return self.fget.__get__(instance, owner)()
K:\Automatic1111-Stable-Diffusion\py310\lib\site-packages\torch\storage.py:899: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  storage = cls(wrap_storage=untyped_storage)
Creating model from config: K:\Automatic1111-Stable-Diffusion\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Loading VAE weights specified in settings: K:\Automatic1111-Stable-Diffusion\models\VAE\kl-f8-anime2.ckpt
K:\Automatic1111-Stable-Diffusion\modules\safe.py:30: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  return TypedStorage()
Applying xformers cross attention optimization.
Textual inversion embeddings loaded(36): AylaVam, claireOobleksd15-Final, h4nn4uwu, pureerosface_v1, ulzzang-6500-v1.1, corneo_anal, corneo_ball_gag, corneo_covering_breasts_arms_crossed, corneo_covering_breasts_one_arm, corneo_covering_breasts_two_hands, corneo_cowgirl, corneo_pov_oral, corneo_side_doggy, corneo_x_pasties, footjob_positionv2, gunslinger, lop, micromini, ohmyfrick_yogapuss, realcumAI, rsc, sling_bikini, spreadassms, zauber_vore_hardcore, AuroraNegative, bad-artist-anime, bad-artist, bad-hands-5, bad-picture-chill-75v, badhandv4, deformityv6, easynegative, ng_deepnegative_v1_75t, verybadimagenegative_v1.2-6400, charturnerv2, cry5t415ku11
Model loaded in 14.4s (load weights from disk: 0.6s, create model: 0.4s, apply weights to model: 10.6s, apply channels_last: 0.5s, apply half(): 0.6s, load VAE: 0.2s, move model to device: 0.5s, load textual inversion embeddings: 1.0s).
K:\Automatic1111-Stable-Diffusion\py310\lib\site-packages\gradio\deprecation.py:43: UserWarning: You have unused kwarg parameters in Row, please remove them: {'equal_height': True}
  warnings.warn(
K:\Automatic1111-Stable-Diffusion\py310\lib\site-packages\gradio\deprecation.py:43: UserWarning: You have unused kwarg parameters in Slider, please remove them: {'default': 0}
  warnings.warn(
K:\Automatic1111-Stable-Diffusion\py310\lib\site-packages\gradio\utils.py:951: UserWarning: Expected 1 arguments for function <function Script.ui.<locals>.<lambda> at 0x000001E88FE15900>, received 0.
  warnings.warn(
K:\Automatic1111-Stable-Diffusion\py310\lib\site-packages\gradio\utils.py:955: UserWarning: Expected at least 1 arguments for function <function Script.ui.<locals>.<lambda> at 0x000001E88FE15900>, received 0.
  warnings.warn(
K:\Automatic1111-Stable-Diffusion\py310\lib\site-packages\gradio\deprecation.py:43: UserWarning: You have unused kwarg parameters in Tab, please remove them: {'open': False}
  warnings.warn(
K:\Automatic1111-Stable-Diffusion\py310\lib\site-packages\gradio\utils.py:951: UserWarning: Expected 1 arguments for function <function Script.ui.<locals>.<lambda> at 0x000001E89C2EB400>, received 0.
  warnings.warn(
K:\Automatic1111-Stable-Diffusion\py310\lib\site-packages\gradio\utils.py:955: UserWarning: Expected at least 1 arguments for function <function Script.ui.<locals>.<lambda> at 0x000001E89C2EB400>, received 0.
  warnings.warn(
[Discord Rich Presence]  Running Discord Rich Presence Extension, version 1.1.0
[Discord Rich Presence]  Bug reporting -> https://github.com/davehornik/sd-discord-rich_presence
[Discord Rich Presence]  'pypresence' module is installed - skipping.
Error executing callback ui_tabs_callback for K:\Automatic1111-Stable-Diffusion\extensions\sd-discord-rich_presence\scripts\webui-rpc.py
Traceback (most recent call last):
  File "K:\Automatic1111-Stable-Diffusion\modules\script_callbacks.py", line 125, in ui_tabs_callback
    res += c.callback() or []
  File "K:\Automatic1111-Stable-Diffusion\extensions\sd-discord-rich_presence\scripts\webui-rpc.py", line 147, in on_ui_tabs
    start_rpc()
  File "K:\Automatic1111-Stable-Diffusion\extensions\sd-discord-rich_presence\scripts\webui-rpc.py", line 32, in start_rpc
    rpc = pypresence.Presence(client_id)
  File "K:\Automatic1111-Stable-Diffusion\py310\lib\site-packages\pypresence\presence.py", line 13, in __init__
    super().__init__(*args, **kwargs)
  File "K:\Automatic1111-Stable-Diffusion\py310\lib\site-packages\pypresence\baseclient.py", line 28, in __init__
    raise DiscordNotFound
pypresence.exceptions.DiscordNotFound: Could not find Discord installed and running on this machine.

K:\Automatic1111-Stable-Diffusion\py310\lib\site-packages\gradio\deprecation.py:43: UserWarning: You have unused kwarg parameters in Button, please remove them: {'full_width': True}
  warnings.warn(
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 29.9s (import torch: 1.5s, import gradio: 1.1s, import ldm: 0.5s, other imports: 0.9s, load scripts: 4.5s, load SD checkpoint: 14.7s, create ui: 6.2s, gradio launch: 0.4s).
K:\Automatic1111-Stable-Diffusion\modules\safe.py:30: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  return TypedStorage()

---

</p></details>

python: 3.10.11  •  torch: 2.0.0+cu118  •  xformers: 0.0.17  •  gradio: 3.23.0  •  commit: [22bcc7be](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/22bcc7be428c94e9408f589966c2040187245d81)

**Comment by Kepler-16b** [comment]
I looked through the log myself and it seems that your extension only works when discord app is opened, instead I was trying to use it with discord opened in webpage. It is working fine now.
I think this can be added into readme, so others won't have the same issue. Thanks.

**Comment by Edesak** [comment]
Thanks for info. We will add to readme or in console to write it down, so the user knows.
